language: php

php:
  #- 5.4
  - 5.5
  - 5.6
  - '7'
  - hhvm
  #- nightly

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer --prefer-source --dev install

script: vendor/bin/phpunit --coverage-text --debug --verbose

notifications:
  email:
    - pratushnyi@smartling.com
